# Clase 08 

In [1]:
import numpy as np

In [2]:
a = np.array(lst)

NameError: name 'lst' is not defined

lst no está definido anteriormente

-----

## Ejercicios 08 (a)

1. Genere arrays en 2d, cada uno de tamaño 10x10 con:
   1. Un array con valores 1 en la "diagonal principal" y 0 en el resto (Matriz identidad).
   
   2. Un array con valores 0 en la "diagonal principal" y 1 en el resto.
   
   3. Un array con valores 1 en los bordes y 0 en el interior.
   
   4. Un array con números enteros consecutivos (empezando en 1) en los bordes y 0 en el interior.

2. Diga qué resultado produce el siguiente código, y explíquelo
  ```python
  # Ejemplo propuesto por Jake VanderPlas
  print(sum(range(5),-1))
  from numpy import *
  print(sum(range(5),-1))
  ```

-----

### Ejercicio 1

In [4]:
one = np.eye(10)
print(one)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [7]:
two = np.ones([10,10]) - one
print(two)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]


In [9]:
three = np.ones([10,10])
three[:,0] = 0
three[:,-1] = 0
three[0,:] = 0
three[-1,:] = 0
print(three)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
four = np.zeros([10,10])
four[:,0] = np.arange(1,11)
four[-1,:]  = np.arange(10,20)
four[9::-1,-1] = np.arange(20,30)
four[0,9:0:-1] = np.arange(30,39)

print(four)

[[ 1. 38. 37. 36. 35. 34. 33. 32. 31. 30.]
 [ 2.  0.  0.  0.  0.  0.  0.  0.  0. 28.]
 [ 3.  0.  0.  0.  0.  0.  0.  0.  0. 27.]
 [ 4.  0.  0.  0.  0.  0.  0.  0.  0. 26.]
 [ 5.  0.  0.  0.  0.  0.  0.  0.  0. 25.]
 [ 6.  0.  0.  0.  0.  0.  0.  0.  0. 24.]
 [ 7.  0.  0.  0.  0.  0.  0.  0.  0. 23.]
 [ 8.  0.  0.  0.  0.  0.  0.  0.  0. 22.]
 [ 9.  0.  0.  0.  0.  0.  0.  0.  0. 21.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 20.]]


### Ejercicio 2

In [45]:
# Ejemplo propuesto por Jake VanderPlas
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


En la primer línea estamos llamando a la función sum() de Python
En la segunda, estamos importando todos los elementos de numpy de modo que no sea necesario usar la notación numpy.sum(), por ejemplo
En la tercera, estamos llamando a la función numpy.sum() que opera de forma distinta a la correspondiente en Python. Esta es tal que cuando se dice que arranque de -1, realmente arranca de -1, no del elemento -1

Cuando importamos funciones de esa manera hay que tener cuidado porque podemos estar pisando funciones ya existentes y provocando comportamientos no esperados

-----

## Ejercicios 08 (b)

3. Escriba una función `suma_potencias(p, n)` (utilizando arrays y **Numpy**) que calcule la operación $$s_{2} = \sum_{k=0}^{n}k^{p}$$. 

4.   Usando las funciones de numpy `sign` y `maximum` definir las siguientes funciones, que acepten como argumento un array y devuelvan un array con el mismo *shape*:
  - función de Heaviside, que vale 1 para valores positivos de su argumento y 0 para valores negativos.
  **Cómo comparo ndarrays?**
  - La función escalón, que vale 0 para valores del argumento fuera del intervalo $(-1,1)$ y 1 para argumentos en el intervalo.
  - La función rampa, que vale 0 para valores negativos de $x$ y $x$ para valores positivos.

-----

### Ejercicio 3

In [3]:
import numpy as np
test = np.arange(1,10,1)
print(test)

[1 2 3 4 5 6 7 8 9]


In [5]:
def suma_potencias(p,n):
    k_array = np.arange(0,n+1,1)
    k_array_to_p = k_array**p
    suma = np.sum(k_array_to_p)

    return suma

suma_potencias(2,3)

14

### Ejercicio 4

The sign function returns -1 if x < 0, 0 if x==0, 1 if x > 0. nan is returned for nan inputs.

maximum: Compare two arrays and returns a new array containing the element-wise maxima

In [6]:
x1 = [1,2,3]
x2 = [2,2,1]
np.maximum(x1,x2)

array([2, 2, 3])

In [24]:
def Heaviside(x):
    #Si hago la siguiente comparación no puedo tomar ndarrays
    # if x == 0:
    #     return float('NaN')
    # else:    
    return (np.sign(x)/2) + 0.5

test = np.array([-2,-1, -0.5, 0, 0.5, 1.,2])
Heaviside(test)

array([0. , 0. , 0. , 0.5, 1. , 1. , 1. ])

In [25]:
def escalon(x):
    return  Heaviside(x+1) - Heaviside(x-1)

escalon(test)

array([0. , 0.5, 1. , 1. , 1. , 0.5, 0. ])

In [26]:
def rampa(x):
    zeros = np.zeros(len(x))
    return np.maximum(zeros, x)

rampa(test)

array([0. , 0. , 0. , 0. , 0.5, 1. , 2. ])


5. **Caída libre** Cree una función que calcule la posición y velocidad de una partícula en caída libre para condiciones iniciales dadas ($h_{0}$, $v_{0}$), y un valor de gravedad dados. Se utilizará la convención de que alturas y velocidades positivas corresponden a vectores apuntando hacia arriba (una velocidad positiva significa que la partícula se aleja de la tierra). 

La función debe realizar el cálculo de la velocidad y altura para un conjunto de tiempos equiespaciados. 
Los valores de velocidad inicial, altura inicial, valor de gravedad, y número de puntos deben ser argumentos de la función con valores por defecto adecuadamente provistos. La tabla de valores debe darse hasta que la partícula toca el piso (valor $h=0$).

Guarde los resultados en tres columnas (t, v(t), h(t)) en un archivo de nombre "caida_vel_alt.dat"
donde "vel" corresponde al valor de la velocidad inicial y "alt" al de la altura inicial.


### Ejercicio 5

In [41]:
#a = -g
#v = -g*t + v0
#z = -g/2*t**2 + v0*t + h0

def dinamica(h0=0,v0=0,g=10, N=1):
    #Desde t = 0 hasta t tal que h = 0
    
    #t array
    t0 = 0
    tmax = (-v0 - np.sqrt(v0**2 - 4*(-g/2)*h0))/(-g)
    t_array = np.linspace(t0,tmax, N)

    #h_array
    h_array = -g/2*t_array**2 + v0*t_array + h0

    #v_array
    v_array = -g*t_array + v0

    #Guardo los resultados
    archivo = f"caida_{v0}_{h0}.dat"

    np.savetxt(archivo, np.array([t_array, v_array, h_array]).transpose())

dinamica(1,1,N = 10)




6. **PARA ENTREGAR** Queremos realizar numéricamente la integral
  $$
  \int_{a}^{b}f(x)dx
  $$
  utilizando el método de los trapecios. Para eso partimos el intervalo $[a,b]$ en $N$ subintervalos y aproximamos la curva en cada subintervalo por una recta

![](figuras/trapez_rule_wiki.png)

  La línea azul representa la función $f(x)$ y la línea roja la interpolación por una recta (figura de https://en.wikipedia.org/wiki/Trapezoidal_rule)

  Si llamamos $x_{i}$ ($i=0,\ldots,n,$ con $x_{0}=a$ y $x_{n}=b$) los puntos equiespaciados, entonces queda
  $$
     \int_{a}^{b}f(x)dx\approx\frac{h}{2}\sum_{i=1}^{n}\left(f(x_{i})+f(x_{i-1})\right).
  $$

  * Escriba una función  `trapz(x, y)` que reciba dos arrays unidimensionales `x` e `y` y aplique la fórmula de los trapecios.

  * Escriba una función `trapzf(f, a, b, npts=100)` que recibe una función `f`, los límites `a`, `b` y el número de puntos a utilizar `npts`, y devuelve el valor de la integral por trapecios.

  * Calcule la integral logarítmica de Euler:
  $$\mathrm{Li}(t) = \int_2^t \frac{1}{\ln x} dx$$
  usando la función ´trapzf´ para valores de `npts=10, 20, 30, 40, 50, 60`

**NOTA:** Envíe el programa llamado **08_Suapellido.py** en un adjunto por correo electrónico, con asunto: **08_Suapellido**.

-----

In [58]:
def trapz(x,y):
    '''
    Aplica la fórmula de los trapecios a los arrays unidimensionales x e y
    (https://en.wikipedia.org/wiki/Trapezoidal_rule)
    
    Parameters
    ----------
    x: ndarray
    y: ndarray

    Returns
    -------
    float: resultado de aplicar la fórmula de los trapecios

    '''
    h = x[1] - x[0] #Asumiendo que están equiespaciados

    #Creo los términos que voy a sumar
    f_xi = y[1:] #ndarray de términos f(x_i)
    f_xii = y[0:-1] #ndarray de términos f(x_{i-1})
    
    return h/2*np.sum(f_xi + f_xii)


In [59]:
def trapzf(f,a,b,npts = 100):
    '''
    Calcula el valor de la integral por trapecios

    Parameters
    ----------
    f: función
    a, b: límites inferior y superior
    npts: número de puntos a utilizar
    
    '''
    #Creo el array x
    x_array = np.linspace(a,b,npts)

    #Creo el array y. Asumo por defecto que f no es capaz de tomar ndarrays como entrada
    y_array = np.zeros(npts)
    for i in range(npts):
        y_array[i] = f(x_array[i])

    return trapz(x_array,y_array)

In [84]:
def f_Euler(x):
    '''
    Integrando de la integral logarítmica de Euler
    '''
    return 1/np.log(x)

def Li(t,npts):
    '''
    Calcula la integral logarítmica de Euler mediante el método de trapecios

    Parameters
    ----------
    t: límite superior de la integral
    npts: número de puntos a utilizar en el método de trapecios

    '''

    return trapzf(f_Euler, 2, t, npts)


#Calculo la integral (test)

# t = 10
# print(f"Test: para t = {t}")
# print("npts", "valor", sep = "\t")
# npts_array = np.arange(10,61,10)
# integral = np.zeros(len(npts_array))
# for i in range(len(npts_array)):
#     print(npts_array[i], Li(t, npts_array[i]), sep = "\t")


Test: para t = 10
npts	valor
10	5.183687078923064
20	5.135288033966899
30	5.126868979384902
40	5.124004191477378
50	5.122699629466988
60	5.121998485280046


In [78]:
x_array = np.linspace(1,2,10)
h_Pablo = x_array[1]-x_array[0]
h_Gasti = (x_array[-1] - x_array[0])/np.shape(x_array)[0]