# Clase 08 

In [1]:
import numpy as np

In [2]:
a = np.array(lst)

NameError: name 'lst' is not defined

lst no está definido anteriormente

-----

## Ejercicios 08 (a)

1. Genere arrays en 2d, cada uno de tamaño 10x10 con:
   1. Un array con valores 1 en la "diagonal principal" y 0 en el resto (Matriz identidad).
   
   2. Un array con valores 0 en la "diagonal principal" y 1 en el resto.
   
   3. Un array con valores 1 en los bordes y 0 en el interior.
   
   4. Un array con números enteros consecutivos (empezando en 1) en los bordes y 0 en el interior.

2. Diga qué resultado produce el siguiente código, y explíquelo
  ```python
  # Ejemplo propuesto por Jake VanderPlas
  print(sum(range(5),-1))
  from numpy import *
  print(sum(range(5),-1))
  ```

-----

### Ejercicio 1

In [4]:
one = np.eye(10)
print(one)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [7]:
two = np.ones([10,10]) - one
print(two)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]


In [9]:
three = np.ones([10,10])
three[:,0] = 0
three[:,-1] = 0
three[0,:] = 0
three[-1,:] = 0
print(three)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
four = np.zeros([10,10])
four[:,0] = np.arange(1,11)
four[-1,:]  = np.arange(10,20)
four[9::-1,-1] = np.arange(20,30)
four[0,9:0:-1] = np.arange(30,39)

print(four)

[[ 1. 38. 37. 36. 35. 34. 33. 32. 31. 30.]
 [ 2.  0.  0.  0.  0.  0.  0.  0.  0. 28.]
 [ 3.  0.  0.  0.  0.  0.  0.  0.  0. 27.]
 [ 4.  0.  0.  0.  0.  0.  0.  0.  0. 26.]
 [ 5.  0.  0.  0.  0.  0.  0.  0.  0. 25.]
 [ 6.  0.  0.  0.  0.  0.  0.  0.  0. 24.]
 [ 7.  0.  0.  0.  0.  0.  0.  0.  0. 23.]
 [ 8.  0.  0.  0.  0.  0.  0.  0.  0. 22.]
 [ 9.  0.  0.  0.  0.  0.  0.  0.  0. 21.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 20.]]


### Ejercicio 2

In [45]:
# Ejemplo propuesto por Jake VanderPlas
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


En la primer línea estamos llamando a la función sum() de Python
En la segunda, estamos importando todos los elementos de numpy de modo que no sea necesario usar la notación numpy.sum(), por ejemplo
En la tercera, estamos llamando a la función numpy.sum() que opera de forma distinta a la correspondiente en Python. Esta es tal que cuando se dice que arranque de -1, realmente arranca de -1, no del elemento -1

Cuando importamos funciones de esa manera hay que tener cuidado porque podemos estar pisando funciones ya existentes y provocando comportamientos no esperados

-----

## Ejercicios 08 (b)

3. Escriba una función `suma_potencias(p, n)` (utilizando arrays y **Numpy**) que calcule la operación $$s_{2} = \sum_{k=0}^{n}k^{p}$$. 

4.   Usando las funciones de numpy `sign` y `maximum` definir las siguientes funciones, que acepten como argumento un array y devuelvan un array con el mismo *shape*:
  - función de Heaviside, que vale 1 para valores positivos de su argumento y 0 para valores negativos.
  - La función escalón, que vale 0 para valores del argumento fuera del intervalo $(-1,1)$ y 1 para argumentos en el intervalo.
  - La función rampa, que vale 0 para valores negativos de $x$ y $x$ para valores positivos.

-----